### PR TITLE
[Style] Addition of the support of background-image-repeat

### PR DESCRIPTION
**Pull request by tfabretti**
Hi again ! :D
I thought I could delete the branch and add another to the pull request bu it turns out I can't, so i recreated the PR #40 (linked to issue #39) :P
Sorry, I'm still struggling with Git and Github :(

### CODE REVIEW

**Comment by ianharrigan** [comment]
Still not sure its right im afraid... in your PR there is code being added for "drawRoundedRect", this was removed and your PR is re-adding it, which makes me cautious about what else it might be re-adding. If i were you it might make sense to close this PR, and make sure you have the most up to date version of haxeui-heaps (which presumably you dont currently), and then "redo" your changes. PITA for sure though... :/

**Comment by tfabretti** [comment]
Ah ! I made a bad merge, at some point. Then, I didn't check closely enough. Since it was after my new function, I missed it being an entirely other function ^^'

**Comment by tfabretti** [comment]
I've fixed the merging to make sure I didn't erase some new stuff, it should be alright, now :D

**Comment by ianharrigan** [comment]
Great, thanks for this! :)

**Pull request merged**
